### ISSUE TITLE
สอบถามเรื่อง stalemate กับ performance ครับ

### ISSUE THREAD

**Issue by 51616** [witchu/alphazero#1]
ถ้าเกมเล่นไปเรื่อย ๆ แล้วไม่มีวันจบ อย่างเช่น มีฮอสฝั่งละ 1 ตัว ตอนนี้ทำการแก้ไขยังไงหรอครับ?
แล้ว performance ของ model นี้ ถึง superhuman รึยังครับ หรือยังแพ้คนทั่วไปอยู่ครับ

**Comment by witchu** [comment]
ตัว state ของ หมากฮอสมีตั้งไว้ครับว่าถ้าไม่มีการกินหรือเดินเบี้ยติดต่อกัน 16 ครั้ง จะเสมอครับ [ดูโค้ด](https://github.com/witchu/alphazero/blob/9bafff030ef6fca35e44754233bf54395ac63873/makhos/state.py#L45)

ผมใช้ GPU เทรนไป 2-3 เดือน ยังสู้ตัวที่ผมเขียนด้วย Minimax depth 10-12 ไม่ได้ครับ น่าจะต้องมา tune model ให้ดีกว่านี้ก่อนครับ

**Comment by 51616** [comment]
ขอบคุณครับ :)
